sudo: required
services:
  - docker

before_install:
  - docker build -t suhas -f Dockerfile.dev .

script:
  - docker run suhas npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker1"
  env: "Docker1-env"
  bucket_name: "elasticbeanstalk-us-east-1-590183718915"
  bucket_path: "docker1"
  on:
    branch: master